#! /bin/bash
__symfony_completer_complete()
{
    local cur
    _get_comp_words_by_ref -n : cur
    words=$(symfony-completer completer --COMP_CWORD "$COMP_CWORD" --COMP_LINE "$COMP_LINE" --COMP_POINT "$COMP_POINT" --COMP_WORDBREAKS "$COMP_WORDBREAKS" --COMP_WORDS "$COMP_LINE" )
    if [ $? -eq 0 ]; then
        mapfile -t COMPREPLY < <(echo "$words")
    else
        COMPREPLY=($(compgen -o filenames -A file $cur))
    fi
    __ltrim_colon_completions "$cur"
    return 0
}
